//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork_Form
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblLectures> tblLectures { get; set; }
        public virtual DbSet<tblNotes> tblNotes { get; set; }
        public virtual DbSet<tblStudent> tblStudent { get; set; }
        public virtual DbSet<tblSchoolClubs> tblSchoolClubs { get; set; }
    
        public virtual ObjectResult<NOTELIST_Result> NOTELIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NOTELIST_Result>("NOTELIST");
        }
    }
}
